server:
  port: 8081
spring:
  datasource:
    url: jdbc:mysql://121.41.2.141:3307/ry?useUnicode=true&characterEncoding=utf-8&useSSL=false&jdbcCompliantTruncation=false&zeroDateTimeBehavior=convertToNull&serverTimezone=GMT%2B8
    username: root
    password: toor952&
    driver-class-name: com.mysql.jdbc.Driver

