server:
  port: 8081
spring:
  datasource:
    url: jdbc:mysql://121.1.1.1:3306/ry?useUnicode=true&characterEncoding=utf-8&useSSL=false&jdbcCompliantTruncation=false&zeroDateTimeBehavior=convertToNull&serverTimezone=GMT%2B8
    username: user
    password: password
    driver-class-name: com.mysql.jdbc.Driver

