server:
  port: 8081
spring:
  datasource:
    url: jdbc:mysql://121.41.2.141:3307/ry?useUnicode=true&characterEncoding=utf-8&useSSL=false&jdbcCompliantTruncation=false&zeroDateTimeBehavior=convertToNull&serverTimezone=GMT%2B8
    username: root
    password: toor952&
    driver-class-name: com.mysql.jdbc.Driver

yeafel:
  cookie: _ntes_nnid=330e001a0bc1e2b81ebaf2992302a68a,1700737832997; _ntes_nuid=330e001a0bc1e2b81ebaf2992302a68a; Device-Id=PMT1ZU91DupswMenUPY2; nts_mail_user=kfy166666@163.com:-1:1; NTES_P_UTID=Ml0JrCLFXI4e8rSgKM1z0s58IluEPc8E|1713411484; P_INFO=m15083727072@163.com|1713411707|0|unireg|00&99|null&null&null#jis&321100#10#0#0|150072&1||15083727072@163.com; timing_user_id=time_aRyzg7nihr; remember_me=U1074831596|1lwisqRDRMA0lH2KElZAvyInmRjWPN3U; session=1-slxo0kXvp2wnP9fcQHcB8Pezz7lANl1Bn-G1ukWWOGpY2027831220; Locale-Supported=zh-Hans; game=csgo; csrf_token=IjA1MTRkZTUyNzFiMTNmMDRlNzQ2YTc3NWFlMzEyOGVhNGM5MGY4NTci.GQbR2A.7Qxq8wXt3Ju26MLnUs7utxjr0gk
  c5cookie: ""